### ISSUE TITLE
Brightness validation can wrongly refuse a theme when no day/nighthighlight is given

### ISSUE THREAD

**Issue by Khosmon** [t1m0thyj/WDD-themes#31]
If there are no `dayHighLight` referenced in `theme.json`, and images are not in incremental order in the `dayImageList` section, the function `validate_image_brightness` can fail to get the image just before (or after) the middle of the list, as [it seek the ±1 of it](https://github.com/t1m0thyj/WDD-themes/blob/f9a397dbfe659b078e595f6c7c747d6a1e1e9b7f/main.py#L221), and will compare values with wrong ids. Also apply for [night](https://github.com/t1m0thyj/WDD-themes/blob/f9a397dbfe659b078e595f6c7c747d6a1e1e9b7f/main.py#L223).

## Here is an example

Let says `theme.json` contains the following:

```JSON
  "dayImageList": [
    1,
    5,
    6
  ],
``` 
and the actual brightest image of all is id **1**.

The script will define `expected_light_id` as the middle image of the list, which is **5** ; and test around **5±1**, whose are **4** and **6** – as if image ids **4**, **5** and **6** should be the brightest. In this situation, id **1** is not in the interval, and the script refuses to validate. If **1** was named **4**, the script will validate the theme.

The script should get the immediate previous and next items from the middle of the collection, whose are images ids **1** and **6**. The validation passes if the actual brightest image is one among 1, 5 and 6.

## Suggestion of fix

The lambda expression to get the middle item of a list can be improved to take an optional parameter `offset` which will return an offset item from de middle of the list. By default, if omitted, `offset` = `0`. It also return `None` otherwise, instead of `-1`:
```PYTHON
get_middle_item = lambda list, offset = 0: list[(len(list) // 2) + offset] if list else None
```

I also rewrote the function (because I wanted the test to be performed locally). Instead of a list, I used a dictionary as it create a stronger relationship between and image id and its mean. I also compose a list of candidate of expected, populated either by the `dayhightlight` when provided, or by 3 ids from the list. I decided to rely on the image name instead of extracting the id from it, because I preferred that way. This code is not perfect: It can't manage daylist of less of 3 items, and it have many calls of the lambda expression to get items around the middle of a list, instead of returning a sublist. It also doesn't manage cases where different images are equally the brightest.

```PYTHON
def validate_brightest_image(theme_config, working_path):
    os.chdir(working_path)
    # get a dict<filename:string, mean:int> of all images to scan them
    image_pattern = theme_config.get("imageFilename")
    image_filenames = {}.fromkeys(glob.glob(image_pattern))

    # generate an image statistics for each images
    for an_imagefile in image_filenames:
        this_image = Image.open(an_imagefile).convert("L")
        this_image_stats = ImageStat.Stat(this_image)
        image_filenames[an_imagefile] = this_image_stats.mean[0]

    # get the brightest observed image from the list
    actual_brightest_image = max(image_filenames, key=lambda key: image_filenames[key])

    # get the brightest referenced image OR 3 images near the middle of the daylist
    ref_brightest_files = []
    if theme_config.get("dayHighlight"):
        ref_brightest_files.append(image_pattern.replace("*", str(theme_config.get("dayHighlight"))))
    else:
        # if not highlight is given in theme.json, we suppose that brightest images are near the middle of the day
        ref_brightest_files.append(get_middle_item(theme_config("dayImageList")))
        ref_brightest_files.append(get_middle_item(theme_config("dayImageList", -1)))
        ref_brightest_files.append(get_middle_item(theme_config("dayImageList", +1)))
        # Not an elegante code...

    # do the check actual vs selected references
    if actual_brightest_image not in ref_brightest_files:
        raise Exception(f"Brightest image is {actual_brightest_image}, but referenced image is {ref_brightest_files[0]}.")
        # Note that the error doesn't tell the ±1 around the middle.

```

Feel free to do as you please, and, in any case, have a good day!

**Comment by t1m0thyj** [comment]
Thanks for reporting this and catching my bug with the interval being tested 🙂 I've decided to relax this validation to only check that the brightest image is in the dayImageList, and the darkest image is in the nightImageList: https://github.com/t1m0thyj/WDD-website/blob/master/_src/discord-bot.py#L66-L77
